version: '3'
services:
  frontend-server:
    build: 
      context: ./frontend-server
    container_name: frontend-container
    ports:
      - "8000:8000"
    volumes:
      - .\frontend-server\src:/app/src
    networks:
      internal-network:
        ipv4_address: 172.18.0.6
    depends_on:
      - catalog-server
      - order-server

  order-server:
    build:  
      context: ./order-server
    container_name: order-container
    ports:
      - "8002:8002"
    volumes:
      - .\order-server\src:/app/src
    networks:
      internal-network:
        ipv4_address: 172.18.0.8

    depends_on:
      - catalog-server

  catalog-server:
    build: 
      context: ./catalog-server
    container_name: catalog-container
    ports:
      - "8001:8001"
    volumes:
      - .\catalog-server\src:/app/src
      - .\catalog-server\catalog.db:/app/catalog.db
    networks:
      internal-network:
        ipv4_address: 172.18.0.7

networks:
  internal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16