version: '3'
services:
  frontend-server:
    build:
      context: . 
      dockerfile: ./front-server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    networks:
      - internal-network
    depends_on:
      - order-server
      - catalog-server

  order-server:
    build:  
      context: . 
      dockerfile: ./order-server/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app
    networks:
      - internal-network
    depends_on:
      - catalog-server

  catalog-server:
    build:  
      context: . 
      dockerfile: ./catalog-server/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8001:8001"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
