version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - order-server
      - catalog-server

  order-server:
    build:
      context: ./order-server
    ports:
      - "8000:8000"
    networks:
      - internal-network
    depends_on:
      - catalog-server

  catalog-server:
    build:
      context: ./catalog-server
    ports:
      - "8001:8001"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
